<?php

//LOCATIONS
LOCATION_INIT = "Location: http://190.111.250.232/doctracer/dclogin.php";
LOCATION_INTOINIT = "Location: http://190.111.250.232/doctracer/dcmain.php";

// ERROR MESSAGES FROM DATABASE 

STR_ICantConnectDb = "No puedo conectarme con la base de datos";
STR_ICantOpenDb = "No puedo abrir la base de datos: ";
STR_ERROR_Password = "No se pudo validar la clave ";
STR_ERROR_ICantRunQuery = "No se pudo ejecutar la consulta: ";


//ERROR MESSAGES FROM LOGIN
STR_ERROR_FIELDREQUIRED = "Se deben llenar todos los campos para poder ingresar";
STR_ERROR_INVALIDPASS =  "Clave incorrecta, inténtelo de nuevo"; 


?>
